apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["watch", "list", "get", "update"]
{{- if .Values.bootstrap }}
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "get", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update"]
{{- end }}